### ISSUE TITLE
Draconic Evolution Recipe Overide

### ISSUE THREAD

**Issue by Voxel-Friend** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#10]
AOBDBB overrides the recipe for the draconium block, and the one it adds does not work with DE's recipes. could possibly be because of code attached to DE's block (Awakening ritual) but I wouldn't know. I thought I ought to bring this to your attention.

**Comment by buttilda** [comment]
DE probably isn't registering their block in the Ore Dictionary or is doing it too late.

**Comment by Voxel-Friend** [comment]
No idea but I'll see about posting over there too.

**Comment by Voxel-Friend** [comment]
Done. https://github.com/brandon3055/Draconic-Evolution/issues/107 if you want to weigh in.

**Comment by Voxel-Friend** [comment]
DE Dev's said they will fix it on their end. Thank you for your time.
