### ISSUE TITLE
Feature request: Configurable Blacklist

### ISSUE THREAD

**Issue by Voxel-Friend** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#12]
Title really says it all, but I just want to add that if I understand if it's too much trouble. Specifically, It would be nice to blacklist specific Items to not generate (to solve futher issues similar to #10) but I would be happy if it even block was for entire catagorys (i.e. yellorium)
As always, thank you for your efforts.

**Comment by buttilda** [comment]
You can block entire metals already, just look in the config file and you'll see a "disable all" option on each metal's config. That will force it to not generate any items or recipes.

As for blacklisting specific items... That would cause issues when adding recipes that depend on those items. AOBD already only adds items if equivalents are present (if a mod is not registering their stuff in the ore dictionary then it's their fault not mine XD), so there is already an effort to keep the items list the least polluted as possible.

**Comment by Voxel-Friend** [comment]
Ah. That make a lot more sense. Thank you for your patience, obviously I have a lot to learn.

**Comment by buttilda** [comment]
No worries :)
