### ISSUE TITLE
Server Crash with RFTool dimensions

### ISSUE THREAD

**Issue by ivardensphere** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#13]
Hello!

got a crash serverside when a player created a RFTools dimension.

https://gist.github.com/ivardensphere/ca4db21e25eace7f984e

Abodbb version: AOBDBB-1.0.3
RFtools version: rftools-3.00beta1
Forge version: .1408

Please let me know if you need more information.

-Combi

**Comment by buttilda** [comment]
Already fixed.
Thanks for the report. I'll release a fix soon :)
