### ISSUE TITLE
Feature Request: Blankberry Bushes

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#16]
Oreberry Bushes that become the type of whatever block type they are on Solid metal or Ore.
This could be useful for gating endless materials behind a certain amount of normal mining.

**Comment by buttilda** [comment]
I see that as a balance issue. And since balance is relative, I don't think I'll be implementing it.
Mod Pack creators that want to gate the bushes usage could simply disable the worldgen and add recipes to them.
