### ISSUE TITLE
Crash with Magneticraft Api

### ISSUE THREAD

**Issue by cout970** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#17]
The mod has been updated, The api is the same but the name of the packages has changed, so the game crashes when the two mods are intalled together. Should be easy fix. 
https://github.com/cout970/Magneticraft-API-and-Issues
Sorry about changing the api so often.

**Comment by buttilda** [comment]
It's okay, I'll fix it as soon as possible :)

**Comment by buttilda** [comment]
Done: https://github.com/ganymedes01/Another-One-Bites-the-Dust/commit/cbf76edf30de064856e6b6c5670d7c171912e178
