### ISSUE TITLE
[FEATURE] Add thaumcraft integration

### ISSUE THREAD

**Issue by hron84** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#18]
Thaumcraft golems currently cannot harvest AOBDBB bushes, unlike TiCon bushes. Please. please make it possible... :-)

AOBD 2.8.4
AOBDBB 1.0.5
Thaumcraft 4.2.3.5

**Comment by buttilda** [comment]
Should be easy enough. I'll see about adding it :)

**Comment by buttilda** [comment]
Just checked the code and I actually add integration for the golems already.
Have you tried it? It should be working D=

**Comment by hron84** [comment]
I checked it, and golems cannot farm bushes. But I'm online on the server, I re-check it again.

**Comment by hron84** [comment]
Errm... I dunno how it happened, but it seems like the golem breaks the whole block - not just right-click harvest them. I have a order upgrade (that makes golem to re-plant things) but it's also does not work. So he's slowly destroy the farm - dunno what is the speed of this.

**Comment by buttilda** [comment]
Very strange. I definitely told thaumcraft that they are clickable crops and not right-clickable ones.
I'll do some testing. Thanks for letting me know :3

**Comment by hron84** [comment]
hmm,maybe you mean it opposite? Bushes are right-clickable for players IIRC. This should be good for golems too.

**Comment by buttilda** [comment]
sorry, what I meant was: they are clickable not harvestable

**Comment by buttilda** [comment]
Seems to me like it's a bug within thaumcraft. But i think I can work around it :3
Running some tests right now

**Comment by hron84** [comment]
Sounds cool... :-)

**Comment by buttilda** [comment]
Got it working on my tests :)

**Comment by hron84** [comment]
Can you tell me when can we expect the fix in release? We've to plan the server upgrade...

**Comment by buttilda** [comment]
It's released. Just need to wait until Curse approves it :)

**Comment by hron84** [comment]
Ohh, I very like it. Thanks for your great assistance!

**Comment by buttilda** [comment]
There you go:
http://minecraft.curseforge.com/projects/another-one-bites-the-dust-berry-bushes/files/2263870

Let me know if you run into any other issues

**Comment by hron84** [comment]
@ganymedes01 I'll talk to the server owner few hours later, because here is 01:19 AM and he went asleep.

**Comment by hron84** [comment]
@ganymedes01 we upgraded AOBDBB to the latest release, and golem interactions works quite well, I threw into my furnace more than a stack of platinum berries on this morning. Again, thanks for your great assistance and quick solution for this problem!

**Comment by buttilda** [comment]
I'm glad it's all working as it should :)
Let me know if you run into any other issues
