### ISSUE TITLE
A couple issues, and a few questions

### ISSUE THREAD

**Issue by Azutte** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#2]
- If you plant a bush on top of a fully grown one, the top of the BOTTOM block is completely invisible, the texture just disappears.
- Botania Agricarnations and Thaumcraft Lamps of Growth (lamp of growths?) don't have any effect, at all.
- Any reason why you chose to recolor (what looks like cobblestone) instead of the TiCon bushes? 
- Any reason why you opted to have it so you can completely walk through them?
- Is there even a mod where steel's an ore? Other than this one, of course. Also, why is it adding a steel ore?

**Comment by buttilda** [comment]
-Are you using fast mode?
-Hm, strange, they should be working!
-I don't have permission to use TiC's bush textures.
-You can walk through them because that's how plants in minecraft tend to work
-This mod doesn't add Steel Ore. Do you have Nether Ores? It adds steel ore =P

**Comment by buttilda** [comment]
Tested with the Agricarnation and it's working. I see green particles everywhere. Bushes are slow growing so don't expect them to grow just like wheat would.

**Comment by labpaw** [comment]
@ganymedes01 hmm, you can't walk through TiC's bushes. They will damage you if you are trying to stay on them. Are you sure it's impossible? Maybe if TiC installed it is possible to make your bushes more like TiC's?

**Comment by labpaw** [comment]
Also, you can request permission to use TiC's textures. Maybe authors will allow you to use them.

**Comment by buttilda** [comment]
-I could easily make the bushes hurt players that touch them, but I just don't see a reason why.. It just makes it annoying to harvest them. I'd rather just let people walk through them.

-Yeah I could ask for the textures, but my bushes behave slightly different than theirs, so it's better if they look different too. Though I confess the current texture is not very good =P

**Comment by labpaw** [comment]
1) Maybe a config option for players who like annoyance? :D

**Comment by HanPrower** [comment]
I agree with Adaptivity config for walkthrough/damage/bonemeal would be good.

Configure all the things!! :P

**Comment by buttilda** [comment]
Done =P
