### ISSUE TITLE
Feature request: OreDict Berries

### ISSUE THREAD

**Issue by Voxel-Friend** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#5]
when using JABBA , you can throw TiCon berries into a barrel full of the nuggets they smelt into for unification. Reason is, as far as I can tell, the berries are registered as equivalent to their respective berry via OreDict. If its not to much trouble, do you mind finding a way to do this for yours?

**Comment by buttilda** [comment]
Tinker's Construct register their berries as nuggets and also make them smelt into nuggets... which is quite silly if you ask me. It's like making iron ingots smelt into iron ingots...

My berry bushes can be smelted into nuggets (but aren't register as it), so do that before pumping them into the barrel and it will work :)
