### ISSUE TITLE
Ingot -> nugget recipe broken in other mods when AOBDBB added

### ISSUE THREAD

**Issue by bochen415** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#6]
As title
CoFH ingot -> nugget recipe broken when the addon is installed

Test environment:
https://gist.github.com/bochen415/67e6da18c34e337e5da8

Example: Lead Ingot -> lead nugget

Recipe with AOBDBB:
http://i.imgur.com/WgSwFQ1.png

Recipe without AOBDBB:
http://i.imgur.com/eVVt2Bu.png

Forge 1403

**Comment by buttilda** [comment]
Oh I inverted the metadata with the size parameter. Instead of making a stack with meta 99 and size 9 I made one with meta 9 and size 99. Whoops!

Sorry about that )=

**Comment by buttilda** [comment]
It shouldn't be overriding the recipe though. The recipe added by CoFHCore should still be there. Can you confirm that, please?

**Comment by bochen415** [comment]
Yes, NEI reports the default cofh recipe still intact with AOBDBB. We have a workaround. 
Thanks

**Comment by buttilda** [comment]
Great, so at least you'll be able to keep still play.
Thank you for the report. The fix will be in the next version :)
