### ISSUE TITLE
[Request] Dimension Filtering for World Generation

### ISSUE THREAD

**Issue by UndeadZeratul** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#7]
Would it be possible to add a dimension white/black list to the configuration?  I'd like to be able to configure what dimensions the berry bushes generate in, as our pack has different ores offloaded to their own dimensions for progression.

**Comment by buttilda** [comment]
Sure!
Would you like me to make that per bush or just a general one would do?

**Comment by buttilda** [comment]
Doing it per ore.

**Comment by UndeadZeratul** [comment]
Holy cow that was quick!  Thanks Gany!

**Comment by buttilda** [comment]
No problem ^^
I'll try to release it tomorrow (if time allows), but no promises :)
