### ISSUE TITLE
Nugget cast support?

### ISSUE THREAD

**Issue by Voxel-Friend** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#9]
Not sure if a bug or just not implemented, but cannot pour most metallurgy metals (along with a few others) into nugget cast, even when AOBDBB adds the respective nugget.

**Comment by buttilda** [comment]
There's a nugget cast?

**Comment by buttilda** [comment]
It must be something new because I hadn't heard of it before.

**Comment by Voxel-Friend** [comment]
yes there is.

**Comment by buttilda** [comment]
I'll add support for it when I get home then :3

**Comment by Voxel-Friend** [comment]
Thank you :)

**Comment by buttilda** [comment]
Done :)
https://github.com/ganymedes01/Another-One-Bites-the-Dust/commit/4f46333a627c80b3beec416f888ef2823b5ea285

**Comment by Voxel-Friend** [comment]
Sweet. Much appreciated.
